Fieldapriltags
Team302/2023ChargedUp pull request #329
Opened 2023-03-08 02:42 UTC by muscatd75

2023-03-08 15:06 UTC, nickfrisch commented on src/main/deploy/robot.xml
> +    targetheight="24.125"
Update compBot.xml targetheight and targetheight2 as well.

2023-03-08 15:07 UTC, nickfrisch commented on src/main/deploy/robot.xml
> +      canId="5"
I don't think we should be committing the practicebot xml to main.  Switch robot.xml to be the comp bot's xml, make sure to update targetheights.

2023-03-08 16:00 UTC, nickfrisch requested changes
Just need to have compbot xml updated and put in robot.xml

2023-03-08 16:07 UTC, muscatd75 commented
Not all the changes can be copied to the compbot.xml

Yaw will need calibration on the compbot
Target height and targetheight2 can be copied. I can do the change tonight



On Wed, Mar 8, 2023 at 11:01 AM Nick Frisch ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Just need to have compbot xml updated and put in robot.xml
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Team302/2023ChargedUp/pull/329#pullrequestreview-1330971120>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMDND2PZPBZUIZ3ZT5RYYVTW3CUL3ANCNFSM6AAAAAAVTHPG4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-08 16:09 UTC, muscatd75 commented
Why do we not commit the practice bot xml to main?

On Wed, Mar 8, 2023 at 10:07 AM Nick Frisch ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/deploy/robot.xml
> <https://github.com/Team302/2023ChargedUp/pull/329#discussion_r1129588429>
> :
>
> >    <mechanism
>      type="ARM"
>      networkTable="armNT"
>      controlFile="arm.xml">
>      <motor
>        usage="ARM"
> -      canId="4"
> +      canId="5"
>
> I don't think we should be committing the practicebot xml to main. Switch
> robot.xml to be the comp bot's xml, make sure to update targetheights.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Team302/2023ChargedUp/pull/329#pullrequestreview-1330863641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMDND2NXZARGJXNIFQ3WQZDW3COE3ANCNFSM6AAAAAAVTHPG4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-08 16:13 UTC, nickfrisch commented
> Why do we not commit the practice bot xml to main?
> […](#)

Sorry I could have worded that better, robot.xml on main should contain the compbot values.

2023-03-09 00:10 UTC, nickfrisch approved these changes

2023-03-09 00:23 UTC, merged